### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by prudhvialahari** [jonstoneman/appium-windows-driver#7]
Hi,

I was trying to run automation on Windows Phone using Appium Windows Driver. As I was not able to run automation on Windows Phone, I raised an issue here -- https://github.com/appium/java-client/issues/637.
I came to know that this is not yet supported by WindowsDriver. Probably expecting this could be a feature request for the next release.

Thanks,
Akhil

**Comment by stoneman** [comment]
Hi Akhil,

This driver should be ready to support Windows Phone but is dependent on [WinAppDriver](https://github.com/Microsoft/WinAppDriver) which currently does not.

There is an open issue for adding Windows 10 Mobile support to WinAppDriver here: https://github.com/Microsoft/WinAppDriver/issues/38
